<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.sainsburys.tests.JsonRetrieverTest" tests="3" time="0.113" ignored="0" failures="2" timestamp="09 Nov 2017 18:09:35 GMT" skipped="0" hostname="Joshuas-MBP.home" errors="0">
  <testcase name="jsonResponseShouldContainPineappleProductDetails" time="0.004" classname="com.sainsburys.tests.JsonRetrieverTest">
    <failure type="java.lang.AssertionError" message="expected [{&quot;results&quot;:[{&quot;item-name&quot;:&quot;Sainsbury&#039;s Apples&quot;,&quot;details&quot;:&quot;by Sainsbury&#039;s apples&quot;,&quot;price&quot;:1.75,&quot;calories&quot;:&quot;33&quot;},{&quot;item-name&quot;:&quot;Sainsbury&#039;s Apples&quot;,&quot;details&quot;:&quot;by Sainsbury&#039;s apples&quot;,&quot;price&quot;:1.75,&quot;calories&quot;:&quot;33&quot;}],&quot;total&quot;:3.5}] but found [{&quot;results&quot;:[{&quot;item-name&quot;:&quot;Sainsbury&#039;s Apples&quot;,&quot;details&quot;:&quot;by Sainsbury&#039;s apples&quot;,&quot;price&quot;:1.75,&quot;calories&quot;:&quot;33&quot;}],&quot;total&quot;:1.75}]">
      <![CDATA[java.lang.AssertionError: expected [{"results":[{"item-name":"Sainsbury's Apples","details":"by Sainsbury's apples","price":1.75,"calories":"33"},{"item-name":"Sainsbury's Apples","details":"by Sainsbury's apples","price":1.75,"calories":"33"}],"total":3.5}] but found [{"results":[{"item-name":"Sainsbury's Apples","details":"by Sainsbury's apples","price":1.75,"calories":"33"}],"total":1.75}]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.sainsburys.tests.JsonRetrieverTest.jsonResponseShouldContainPineappleProductDetails(JsonRetrieverTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- jsonResponseShouldContainPineappleProductDetails -->
  <testcase name="testJsonResponseContainsTotalField" time="0.003" classname="com.sainsburys.tests.JsonRetrieverTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [{&quot;results&quot;:[{&quot;item-name&quot;:&quot;Sainsbury&#039;s Apples&quot;,&quot;details&quot;:&quot;by Sainsbury&#039;s apples&quot;,&quot;price&quot;:1.75,&quot;calories&quot;:&quot;33&quot;}],&quot;total&quot;:1.75}]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [{"results":[{"item-name":"Sainsbury's Apples","details":"by Sainsbury's apples","price":1.75,"calories":"33"}],"total":1.75}]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:179)
	at com.sainsburys.tests.JsonRetrieverTest.testJsonResponseContainsTotalField(JsonRetrieverTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testJsonResponseContainsTotalField -->
  <testcase name="jsonResponseShouldContainAppleProductDetails" time="0.106" classname="com.sainsburys.tests.JsonRetrieverTest"/>
</testsuite> <!-- com.sainsburys.tests.JsonRetrieverTest -->
